### ISSUE TITLE
PHP version display consistently 

### ISSUE THREAD

**Issue by juokaz** [philsturgeon/phpversions.info#187]
The data config file has versions stored as just the PATCH version (39 for 6.1.39). Only the `default` key is the full version string.

This makes the display of data confusing. Instead of showing full version strings you have tables of what looks like random numbers. Sometimes question marks. Sometimes RC version strings.

So the fix is to either have the config file use full version strings (easiest, sort might need fixing) or have a jekyll plugin to display the correct version string given the patch version (RC4 -> RC4, 13 -> 5.1.13, ?? -> unknown etc.)

**Comment by philsturgeon** [comment]
You're discribging intent as an accident. The table has a category saying 5.4 then it says 6. That's 5.4.6. This table gets super fucking wide if we double up that data by repeating the major and minor every time.

**Comment by juokaz** [comment]
I'm describing intent as a bad user experience. I get why you did it.

**Comment by philsturgeon** [comment]
The whole site is a bad user experience, I’m just trying not to make it a crowded bad user experience.

Part of a redesign could take care of this. Also killing 5.2 out of here is probably a good idea too.
