### ISSUE TITLE
Parse PHPInfos

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/phpversions.info#191]
- OVH http://fpm7.0-check.cluster015.ovh.net/phpinfo.php
- HostEurope http://php56.hosteurope-infos.de/phpinfo.php

Please add any more you know of in the comments and I'll get this into a Jekyll build step for now, then make something fancy for #82.

**Comment by meli1986** [comment]
* GeekStorage http://goliath.geekstorage.com/~goliath/phpinfo.php - append (70|56|55|54|) for specific version

**Comment by philsturgeon** [comment]
Done! Thanks for posting new ones up.
