### ISSUE TITLE
1&1 PHP "beta"

### ISSUE THREAD

**Issue by TazeTSchnitzel** [philsturgeon/phpversions.info#196]
1&1 [say they offer PHP 7 beta](http://www.1and1.co.uk/hosting-linux?__lf=Order-Product) (under "Tools"), providing [very little in the way of specifics](http://www.1and1.co.uk/details-php-programming?__lf=Order-Product).

Should they be on the PHP 7 page? If so, as what?

**Comment by philsturgeon** [comment]
I don't feel the need to bend over backwards for 1&1, maybe just wait and see if you spot a "PHP 7.0 stable" announcement?

**Comment by TazeTSchnitzel** [comment]
Sounds like an idea.

**Comment by TazeTSchnitzel** [comment]
Oh, looks like they really do mean the beta. Beta 1. https://community.1and1.com/php-7-first-look-beta-1/

**Comment by philsturgeon** [comment]
Ok, let’s embarrass em. bf7212c



-- 
Phil Sturgeon

I talk about turtles, bikes and code over here philsturgeon.uk

**Comment by philsturgeon** [comment]
Ahh thanks for the update 5656ff1

**Comment by TazeTSchnitzel** [comment]
Those few seconds of public exposure must have embarrassed them :p

**Comment by philsturgeon** [comment]
FEELING THE STURGE!

-- 
Phil Sturgeon

I talk about turtles, bikes and code over here philsturgeon.uk
