### ISSUE TITLE
LiquidWeb Information outdated and missing

### ISSUE THREAD

**Issue by mallardduck** [philsturgeon/phpversions.info#279]
LiquidWeb's shared hosting information is missing 5.6.XX.
Additionally LiquidWeb is missing from the managed hosting page. There are offerings of both shared and dedicated hosting types.

I will include pull requests to update these missing or outdated details.

**Comment by mallardduck** [comment]
Alrighty, I've also submitted a new one #282 to fill in the remaining blanks for shared versions.

Once #282 and #278 are merged in this issue will be resolved.

**Comment by philsturgeon** [comment]
Thank you for all of this!

**Comment by mallardduck** [comment]
Not a problem at all Phil!
I'm a fan of the site and was happy to help get the details updated.

I also meddle with developing from time to time myself, I've been eyeing the issue about making version 2 of the site #82 for a few days. So you might see more off me ;)

**Comment by philsturgeon** [comment]
That would be awesome! :D
