### ISSUE TITLE
CI container command breaks on Debian 6 Squeeze check

### ISSUE THREAD

**Issue by afelicioni** [philsturgeon/phpversions.info#285]
On CircleCI container istance, `php ./bin/update-versions` check for Debian 6 breaks, maybe due to LTS ended on 2016-02-29.

`https://packages.debian.org/squeeze/php5` URL used in CI container returns an error, at least human recognizable.
<img width="789" alt="schermata 2016-04-15 alle 18 45 23" src="https://cloud.githubusercontent.com/assets/1416945/14568622/4597f5d0-033a-11e6-8f72-64a14dd0f851.png">

_wheezy_ and _jessie_ URLs are returning useful response

**Comment by philsturgeon** [comment]
Thanks, fixed it!
