### ISSUE TITLE
Some versions parsed from phpinfo are overly verbose

### ISSUE THREAD

**Issue by colinodell** [philsturgeon/phpversions.info#296]
![image](https://cloud.githubusercontent.com/assets/202034/15085008/6fcd2c78-13a5-11e6-96c5-44e09a0a8a1c.png)

Is this the expected behavior or should this show just `7.0.6` instead?

**Comment by philsturgeon** [comment]
This is intentional (its good to show custom patches) but if they’re gonna be that long.. ugh. That’s annoying.

-- 
Phil

On May 6, 2016 at 4:14:18 PM, colinodell (notifications@github.com) wrote:



Is this the expected behavior or should this show just 7.0.6 instead?

**Comment by colinodell** [comment]
Perhaps we could use an `<abbr>` element (or something similar) so that the base version appears with some special styling and the full version with patches appears on hover?

For example:

![image](https://cloud.githubusercontent.com/assets/202034/15085335/a4bfeaae-13a7-11e6-954f-dccc24173c64.png)

**Comment by philsturgeon** [comment]
That would be ideal 

--
Phil Sturgeon

**Comment by colinodell** [comment]
I've implemented this in #349
