### ISSUE TITLE
Separation of shared and custom hosting

### ISSUE THREAD

**Issue by wycks** [philsturgeon/phpversions.info#34]
I think the current graph is confusing , many shared hosts do not offer any versions or upgrades, rather they just have a default. 

Maybe have 2 graphs:
One for shared hosts with only default
One for specialized hosts that allow version switching or upgrades (cloud/VPS/etc).

The real problem is shared hosting and the liability with upgrading a server that might have 5k websites on it.

**Comment by philsturgeon** [comment]
On the case!
