### ISSUE TITLE
Website not updating

### ISSUE THREAD

**Issue by ExoUNX** [philsturgeon/phpversions.info#392]
Appears phpversions.info hasn't updated in a couple months, is this expected?

**Comment by philsturgeon** [comment]
I think its broke, check Travis and see whats up would you?


On May 20, 2017 at 12:03:53 AM, ExoUNX (notifications@github.com) wrote:

Appears phpversions.info hasn't updated in a couple months, is this expected?

**Comment by Krydos1** [comment]
I think once https://github.com/philsturgeon/phpversions.info/pull/395 is merged everything will start working again.

**Comment by ExoUNX** [comment]
Good work, sorry I didn't get a chance to fully to look at it.

**Comment by Kryd0s** [comment]
You're fine. I was trying to add a host and it wouldn't build so I just tracked down the errors to see if I was causing them by adding to hosts.yml.

**Comment by philsturgeon** [comment]
Thanks everyone :D
