### ISSUE TITLE
Site still not updating

### ISSUE THREAD

**Issue by Kryd0s** [philsturgeon/phpversions.info#397]
There are two branches. The default branch master, and the active branch gh-pages. I fixed the fatal errors on the master branch and it builds, but the active branch still isn't updating with the new information. This means the site http://phpversion.info/ isn't updating still. I see a pull on master branch titled "Manual update oops" from @philsturgeon on 2017-05-24, but that doesn't seem to have updated the files on the website either since they all show 2+ months since the last update and new hosts haven't been added. If there is anything I can do to help let me know. :)

**Comment by philsturgeon** [comment]
Looking at the output of ./bin/deploy, auth was failing on github push. It seems like my personal access token was revoked about two months ago, potentially around the time they had that security breach.

I updated that, and switched to the "new" [Travis CI GitHub Pages deployment](https://docs.travis-ci.com/user/deployment/pages/) logic. [Master builds](https://github.com/philsturgeon/phpversions.info/tree/gh-pages) are back, and hopefully so are pull requests and nightly builds.
