### ISSUE TITLE
Good or Bad version

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/phpversions.info#56]
Add a "Secure or not" indicator to PHP versions at the patch level, using output from this https://github.com/psecio/versionscan

For now just put a secure: true/false field in, but we could get really granular later and list actual issues. This would be great at reminding people not to use a certain host, or get people to ask them to update.

**Comment by franz-josef-kaiser** [comment]
Maybe just set a `background: #xxx` of green/red for the table cells.

**Comment by philsturgeon** [comment]
.@enygma showed me an awesome API for this. I'm wondering how to implement it in this crappy Jekyll static system. JavaScript? 

I can make it basically look through all the versions, deduplicate requests, make a bunch of requests and update the background colors with the "red" or "green" to show secure or not. 

I'd LOVE to have a database for this so it can cron job daily to check if each version is secure or not, but the day job is still in the ramp up to launch and I just don't have time for free work right now. Crap solution now, better solution later.

**Comment by philsturgeon** [comment]
Done at a basic red/green level. Showing a "More info" page would be the next job.
